import turtle


phillip = turtle.Turtle()
alice = turtle.Turtle()
peter = turtle.Turtle()
jess = turtle.Turtle()

phillip.shape("turtle")
alice.shape("turtle")
peter.shape("turtle")
jess.shape("turtle")

phillip.fillcolor("yellow")
phillip.begin_fill()

phillip.pendown()
phillip.left(100)
phillip.circle(300)
phillip.end_fill()

alice.fillcolor("white")
alice.begin_fill()

alice.penup()
alice.goto(-200,50)
alice.pendown()
alice.right(90)
alice.circle(75)
alice.end_fill()
alice.fillcolor("black")
alice.begin_fill()
alice.penup()
alice.goto(-120,50)
alice.pendown()
alice.circle(25)
alice.end_fill()

peter.fillcolor("white")
peter.begin_fill()

peter.penup()
peter.goto(-500,50)
peter.pendown()
peter.right(90)
peter.circle(75)
peter.end_fill()
peter.fillcolor("black")
peter.begin_fill()
peter.penup()
peter.goto(-500,50)
peter.pendown()
peter.circle(25)
peter.end_fill()

jess.penup()
jess.goto(-100,-150)
jess.pendown()
jess.fillcolor("pink")
jess.begin_fill()
jess.backward(300)
jess.right(90)
jess.forward(50)
jess.left(90)
jess.forward(300)
jess.left(90)
jess.forward(50)
jess.end_fill()

jess.fillcolor("white")
jess.begin_fill()
jess.left(90)
jess.forward(200)
jess.left(90)
jess.forward(30)
jess.left(90)
jess.forward(40)
jess.left(90)
jess.forward(30)
jess.end_fill()

jess.fillcolor("white")
jess.begin_fill()
jess.left(90)
jess.backward(50)
jess.left(90)
jess.forward(30)
jess.left(90)
jess.forward(40)
jess.left(90)
jess.forward(30)
jess.left(90)
jess.forward(50)
jess.end_fill()

turtle.exitonclick()